name: release

on:
  push:
    branches: master # master 分支提交时触发

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: 签出代码
        uses: actions/checkout@master
      - name: 安装 nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.2"
      - name: 安装依赖
        run: npm install --force
      - name: 前端项目打包
        run: npm run build
      - name: 发布腾讯云
        uses: wlixcc/SFTP-Deploy-Action@v1.0 # 使用 SFTP 协议上传到腾讯云
        with:
          username: 'root'
          server: '${{ secrets.TENCENT_SERVER_HOST }}'
          ssh_private_key: '${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}'
          local_path: './dist/*'
          remote_path: '/home/CICD'
          args: "-o ConnectTimeout=5"
