name: autopublish

on:
  push:
    branches:
      - master # master 分支提交时触发
jobs:
  publish:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: 发布腾讯云
        uses: wlixcc/SFTP-Deploy-Action@v1.0 # 使用 SFTP 协议上传到腾讯云
        with:
          username: "root"
          server: "${{ secrets.TENCENT_SERVER_HOST }}"
          ssh_private_key: "${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}"
          local_path: "./*"
          remote_path: "/home/CICD/jx3dps-online/"
          args: "-o ConnectTimeout=5"
